WIP KP-7159 zip targets
CSCfi/kielipankki-nlf-harvester pull request #51
Opened 2023-10-12 13:26 UTC by Traubert

2023-10-16 09:01 UTC, aajarven requested changes
Looks pretty nice. Fully ditching "image" from our vocabulary is especially nice now that we will have the "visual information depicted as pixel values" type images downloaded too. I didn't scrutinize the renamed stuff (especially in tests) too hard, but as tests pass and the pipeline has actually executed successfully on dev machine (right?) those should be ok. 

There are still some "image" references left, we might want to get rid of these too to rip the terminology band-aid all the way off at once:
```
(.venv) vagrant@kpdev:~/scratch/kielipankki-nlf-harvester/pipeline$ git grep image
...
plugins/operators/custom_operators.py:            file_name_in_image = re.sub("^.+batch_[^/]", "", str(output_file))
plugins/operators/custom_operators.py:                    f"still failing, moving on with image creation"
plugins/operators/custom_operators.py:    - listing the contents of the previous corresponding image into a text
plugins/operators/custom_operators.py:      file if one is found in the given ``image_output_dir``
plugins/operators/file_download_operators.py:        file_name_in_image = re.sub("^.+batch_[^/]", "", str(self.output_file))
plugins/operators/file_download_operators.py:        if file_name_in_image in self.ignore_files_set:
```

2023-10-17 07:12 UTC, Traubert commented on pipeline/dags/download_collections.py
> +                pathdict["OUTPUT_DIR"] / "targets",
Yes, let's do this when / if we get around to it.

2023-10-17 07:13 UTC, Traubert commented on pipeline/plugins/operators/custom_operators.py
> +
Argh, yes, I will make a crappy extra commit to this PR instead of fixing the rebase.

2023-10-17 07:16 UTC, Traubert commented on pipeline/plugins/operators/custom_operators.py
> +            f"unzip -l {self.old_target_path} > {self.file_download_dir}/existing_files.txt"
This is now not used for anything, and we plan to not need it (because we will only fetch changed files), so I guess this should just be dropped.

2023-10-17 07:18 UTC, Traubert commented on remote/update_zip_with_sources.py
> +"""
Not only that, but our no longer needed squashfs stuff also was never provisioned automatically. I should do this.

2023-10-17 07:23 UTC, Traubert commented on remote/update_zip_with_sources.py
> +    )
The idea was to support maybe having downloaded files into various subdirectories of `/local_scratch/` and keeping a list, and giving that list to this. (Although we still would need to decide how to handle their paths in the target zip). So keeping it for now for maybe useful functionality.

2023-10-17 07:24 UTC, Traubert commented on pipeline/dags/download_collections.py
> +    {"id": "col-361", "subset_size": 150},
Right, I'll comment it out.

2023-10-17 12:57 UTC, Traubert commented on pipeline/dags/download_collections.py
> +    "TMPDIR_ROOT": Path(f"/local_scratch/robot_2006633_puhti/harvester"),
Yes.

2023-10-18 07:54 UTC, merged